---
ID: "a259ea90-78ed-4676-a321-a9cac295f37e"
Parent: "c6f107cb-0733-4607-ae42-0cdf9ca70ee9"
Template: "c6f107cb-0733-4607-ae42-0cdf9ca70ee9"
Path: /sitecore/templates/scboilerplate/Foundation/Content Store/Content Store Folder/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181003T120319Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
