---
ID: "1d79075f-e31b-4518-886f-eec9338d72db"
Parent: "7c028025-8f6f-4a3d-84b3-0609260dc0f2"
Template: "7c028025-8f6f-4a3d-84b3-0609260dc0f2"
Path: /sitecore/templates/scboilerplate/Feature/Navigation/_Logo/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181002T054219Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
