---
ID: "9d12a4d5-5e7a-425d-beb3-dbd46ba5d02b"
Parent: "146eeebc-9718-443d-8c3e-bb5c56feb841"
Template: "146eeebc-9718-443d-8c3e-bb5c56feb841"
Path: /sitecore/templates/ilight2019/Foundation/Content Store/Notification/Notification Item/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181018T050233Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
