---
ID: "9452d378-836c-425c-9a16-fbc0d1854457"
Parent: "5d7748fa-1575-46e8-a68d-3d37e8b5b8a5"
Template: "5d7748fa-1575-46e8-a68d-3d37e8b5b8a5"
Path: /sitecore/templates/scboilerplate/Project/Website/Content Types/API/Categories Api/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{399A67A4-57DE-4F9E-B539-1058F174B375}">
        <r
          id="{274BA5C6-41F4-4A4C-8220-2DFF8EC318B1}"
          ph="Content"
          uid="{257E89E4-DE0D-484F-9ABB-22139B3DD1C7}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181003T072522Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
