---
ID: "5cfa8f32-6bb0-40c5-bff4-2ace2c708453"
Parent: "e7c7c48b-2eb0-461c-ac08-16f074fe544c"
Template: "e7c7c48b-2eb0-461c-ac08-16f074fe544c"
Path: /sitecore/templates/scboilerplate/Feature/Navigation/_Footer/__Standard Values
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 300
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180928T093025Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
