---
ID: "7ab7cfe2-f8d1-441f-9672-667d90a5ead8"
Parent: "6a84ef09-dafd-4970-9deb-8b482131ee60"
Template: "6a84ef09-dafd-4970-9deb-8b482131ee60"
Path: /sitecore/templates/ilight2019/Foundation/Content Store/Icons/Icon/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181108T084336Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
