---
ID: "e1715f42-da27-4b76-8675-cf3bff475b43"
Parent: "d25a01bb-98c9-4fe4-8b06-c862244d26a5"
Template: "d25a01bb-98c9-4fe4-8b06-c862244d26a5"
Path: /sitecore/templates/ilight2019/Project/Website/Page Types/Rate Website Form Page/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{7F8A8E38-C582-43CA-B850-D449C5F67D49}">
        <r
          id="{7AFC2F2C-7147-4DE2-8283-922B58EB9B85}"
          ph="HtmlHead"
          uid="{2B477EC8-87BC-4DDD-A035-4D29627083DA}" />
        <r
          id="{4BFFF817-954E-4915-AC6C-5715E08D4192}"
          ph="Main Navigation"
          uid="{BFF3E94C-EB60-4042-A964-C32AD2C4EDA3}" />
        <r
          id="{226CA009-CBA0-4DF0-B475-BFBE16D96402}"
          ph="Content"
          uid="{4A4E6EA1-1E3E-4DE7-BFEB-628987F3B947}" />
        <r
          id="{139F61A2-F940-4C76-94D4-6F70C53C643C}"
          ph="Content"
          uid="{EF4356B2-ECD4-4C15-8FEE-7257AA47F851}" />
        <r
          id="{44140E8E-7967-4E8B-9D2E-613A7375E8A8}"
          ph="Content"
          uid="{45628FCE-447B-47CF-9F32-850ECBC8948E}" />
        <r
          id="{8B62FE6F-6713-48E1-8660-0425DCA36409}"
          ph="Footer"
          uid="{6D3AC5D6-662E-49C2-A7DB-62E3FDFEFE28}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181024T074350Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
