---
ID: "6ca6db4f-c274-4639-992c-5515a516abaa"
Parent: "c2533871-174c-4f91-aaa9-37af7f939d8e"
Template: "c2533871-174c-4f91-aaa9-37af7f939d8e"
Path: /sitecore/templates/scboilerplate/Project/Website/Content Types/API/Api Folder/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181003T072529Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
