---
ID: "c98efdf2-f147-4c6d-98d4-e755d454599a"
Parent: "850361c8-ce44-4f1f-bc65-8fab4fc4ea0b"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/layout/models/ilight2019/Project
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 200
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180926T040228Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
